name: EFB-Agent
options:
  bundleIdPrefix: com.efbagent
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: 6.0.0
targets:
  EFBAgent:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: EFBAgent
        excludes:
          - "**/*.md"
        compilerFlags:
          - -enable-experimental-concurrency
    resources:
      - path: EFBAgent/Resources
      - path: EFBAgent/Assets.xcassets
    info:
      path: EFBAgent/Info.plist
      properties:
        CFBundleDisplayName: EFB Agent
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
    dependencies:
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.efbagent.EFBAgent
        TARGETED_DEVICE_FAMILY: "2" # iPad
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        SWIFT_VERSION: "5.9"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited)"
  EFBAgentTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: EFBAgentTests
    dependencies:
      - target: EFBAgent
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/EFBAgent.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/EFBAgent"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        SWIFT_VERSION: "5.9"

